#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=8,walltime=3:00:00

## modules
module load fsl/5.0.9

echo "Setting file paths"
# Grab the config.json inputs
dwi=`./jq -r '.dwi' config.json`;
bvals=`./jq -r '.bvals' config.json`;
bvecs=`./jq -r '.bvecs' config.json`;
t1=`./jq -r '.t1' config.json`;
echo "Files loaded"

if [ -f "dwi.bvals" ];then
	echo "File exists. Skipping copying of bvals file"
else
	echo "Copying bvals file"
	
	# Copy bvals file
	cp ${bvals} dwi.bvals;
	
	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "Copying failed"
		echo $ret > finished
		exit $ret
	fi
fi

if [ -f "t1.nii.gz" ];then
	echo "File exists. Skipping Orientation and Cropping"
else
	echo "Orienting and cropping t1"

	## Reorient to radiological orientation
	fslreorient2std \
		${t1} \
		t1.nii.gz;

	## Crop out neck and eye tissue
	robustfov \
		-i t1.nii.gz \
		-r t1.nii.gz;

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "Orientation and Cropping failed"
		echo $ret > finished
		exit $ret
	fi
fi

if [ -f "t1_brain.nii.gz" ]; then
	echo "File exists. Skipping T1 brain extraction"
else
	echo "T1 brainmask creation"
	bet t1.nii.gz \
		t1_brain.nii.gz \
		-B \
		-f 0.1 \
		-g 0 \
		-m;

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "T1 brain extraction failed"
		echo $ret > finished
		exit $ret
	fi
fi

if [ -f "nodif_brain.nii.gz" ]; then
	echo "File exists. Skipping b0 brainmask creation."
else	
	echo "Creating b0 brainmask for alignment"
	# Create b0 image
	select_dwi_vols \
		${dwi} \
		${bvals} \
		nodif.nii.gz \
		0;

	# Brain extraction before alignment
	bet nodif.nii.gz \
		nodif_brain \
		-f 0.4 \
		-g 0 \
		-m;

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "b0 brainmask creation failed"
		echo $ret > finished
		exit $ret
	fi
fi
echo "b0 brainmask creation complete"

if [ -f "nodif_acpc.nii.gz" ];then
	echo "Registered file exists"
else
	echo "EPI Image to T1 Registration"
	epi_reg \
		--epi=nodif_brain \
		--t1=t1 \
		--t1brain=t1_brain \
		--out=nodif_acpc;

	flirt \
		-ref nodif_acpc \
		-in ${dwi} \
		-applyxfm \
		-init nodif_acpc.mat \
		-out dwi.nii.gz;

	python -u reslice_fxn.py;
	
	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "Registration failed"
		echo $ret > finished
		exit $ret
	fi
fi
echo "Registration complete"

if [ -f "dwi.bvecs" ];then
	echo "File exists. Skipping Bvec Rotation"
else
	echo "Bvec Rotation"
	matlab -nodisplay -nosplash -r "rotateBvecs()";

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "Rotation failed"
		echo $ret > finished
		exit $ret
	fi
fi
echo "Rotation complete"

echo "Registration Pipeline Complete"


